# Generated by Django 6.0 on 2025-12-26 17:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assesment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assesment_type', models.CharField(choices=[('FT', 'First Terminal'), ('ST', 'Second Terminal'), ('CBT', 'Class Based Test'), ('Final', 'Final Term')])),
                ('max_marks', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.CharField(unique=True)),
                ('subject_name', models.CharField(max_length=200, unique=True)),
                ('full_marks', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.IntegerField()),
                ('marks_obtained', models.IntegerField()),
                ('assesment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resultApi.assesment')),
            ],
        ),
        migrations.AddField(
            model_name='assesment',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resultApi.subject'),
        ),
    ]
