# Generated by Django 6.0 on 2025-12-26 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.IntegerField()),
                ('student_name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField()),
                ('program', models.CharField(max_length=200)),
                ('section', models.CharField(max_length=5)),
                ('enrollment_year', models.DateField()),
                ('active_status', models.BooleanField(default=True)),
            ],
        ),
    ]
