# Generated by Django 5.2.8 on 2025-12-07 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_enrollment_course_alter_enrollment_students'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='students',
            new_name='student',
        ),
    ]
